"""init

Revision ID: 28f81914577b
Revises: 
Create Date: 2022-01-29 00:05:06.903978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f81914577b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('net_id', sa.String(length=20), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(precision=5), nullable=True),
    sa.Column('longitude', sa.Float(precision=5), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_duration'), 'event', ['duration'], unique=False)
    op.create_index(op.f('ix_event_end_time'), 'event', ['end_time'], unique=False)
    op.create_index(op.f('ix_event_net_id'), 'event', ['net_id'], unique=False)
    op.create_index(op.f('ix_event_post_time'), 'event', ['post_time'], unique=False)
    op.create_index(op.f('ix_event_start_time'), 'event', ['start_time'], unique=False)
    op.create_table('first_time',
    sa.Column('net_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('net_id')
    )
    op.create_table('notification_subscribers',
    sa.Column('net_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email_address', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('wants_email', sa.Boolean(), nullable=True),
    sa.Column('wants_text', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('net_id')
    )
    op.create_table('picture',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('event_picture', sa.String(length=1000), nullable=True),
    sa.Column('public_id', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    op.drop_table('notification_subscribers')
    op.drop_table('first_time')
    op.drop_index(op.f('ix_event_start_time'), table_name='event')
    op.drop_index(op.f('ix_event_post_time'), table_name='event')
    op.drop_index(op.f('ix_event_net_id'), table_name='event')
    op.drop_index(op.f('ix_event_end_time'), table_name='event')
    op.drop_index(op.f('ix_event_duration'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
